### ISSUE TITLE
MSlab 24.04 - known issue - MSlab Sending Telemetry fails

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#592] opened 2024-05-04 17:08 UTC
As check with Jaromir there is an expected issues at the moment when script MSlab script are run that would send telemetry.

`Sending telemetry info
New-TelemetryEvent : The term 'New-TelemetryEvent' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.`

![image](https://github.com/microsoft/MSLab/assets/45657752/e25427b6-c7c2-4ed0-a27d-c1cb181d4168)

**Comment by Karl-WE** [comment] 2024-05-28 07:03
@machv @jaromirk seeing the changelog of the latest Release it seems with PR #586 this issue got fixed.

#close ?

**Comment by machv** [comment] 2024-05-28 07:25
Hi @Karl-WE, thanks for pointing this out, I will close it for now, if there would be any other occurrence of said issue, let's reopen this one.

Bug was caused by `PSScriptAnalyzer` remediations for approved verbs.

Thanks!

**Closed by machv** 2024-05-28 07:25 UTC
